import type { ExchangeGroup, PathologyProfile } from '@/types';

export const EXCHANGE_GROUPS: ExchangeGroup[] = [
  { id: 'verdA', name: 'Verduras A/B', kcal: 25, protein: 1.5, fat: 0.2, carbs: 4, fiber: 2, examples: 'Lechuga, tomate, espinacas, pepino, calabacín, berenjena, judías verdes, acelgas' },
  { id: 'verdC', name: 'Verduras C', kcal: 65, protein: 3, fat: 0.3, carbs: 12, fiber: 3, examples: 'Alcachofas, guisantes, remolacha, zanahoria cocida, coles de Bruselas' },
  { id: 'frutA', name: 'Frutas A', kcal: 35, protein: 0.6, fat: 0.2, carbs: 7, fiber: 1.2, examples: 'Fresas, sandía, melón, papaya, pomelo' },
  { id: 'frutB', name: 'Frutas B', kcal: 55, protein: 0.7, fat: 0.3, carbs: 13, fiber: 2, examples: 'Plátano, manzana, pera, naranja, uvas, mango' },
  { id: 'cereal', name: 'Cereales/Tubérculos', kcal: 350, protein: 10, fat: 1.5, carbs: 75, fiber: 3, examples: 'Arroz, pasta, avena, pan, harina (por 100g seco)' },
  { id: 'tuberc', name: 'Tubérculos', kcal: 80, protein: 2, fat: 0.1, carbs: 18, fiber: 2, examples: 'Patata, boniato (por 100g crudo)' },
  { id: 'vacuna', name: 'Vacuna', kcal: 170, protein: 20, fat: 9, carbs: 0, fiber: 0, examples: 'Ternera, buey' },
  { id: 'aves', name: 'Aves', kcal: 120, protein: 22, fat: 3.5, carbs: 0, fiber: 0, examples: 'Pollo, pavo (sin piel)' },
  { id: 'cerdo', name: 'Cerdo', kcal: 160, protein: 20, fat: 8, carbs: 0, fiber: 0, examples: 'Lomo, solomillo' },
  { id: 'conejo', name: 'Conejo', kcal: 130, protein: 21, fat: 4.5, carbs: 0, fiber: 0, examples: 'Conejo' },
  { id: 'pescBlanco', name: 'Pescado blanco', kcal: 90, protein: 18, fat: 1.5, carbs: 0, fiber: 0, examples: 'Merluza, bacalao, lenguado, rape' },
  { id: 'pescAzul', name: 'Pescado azul', kcal: 180, protein: 20, fat: 10, carbs: 0, fiber: 0, examples: 'Salmón, atún, caballa, sardina' },
  { id: 'huevo', name: 'Huevo', kcal: 75, protein: 6.5, fat: 5, carbs: 0.5, fiber: 0, examples: '1 huevo mediano (60g)' },
  { id: 'lecheEnt', name: 'Leche entera', kcal: 130, protein: 6.5, fat: 7.5, carbs: 10, fiber: 0, examples: '200ml leche entera' },
  { id: 'lecheSemi', name: 'Leche semi', kcal: 95, protein: 6.5, fat: 3, carbs: 10, fiber: 0, examples: '200ml leche semidesnatada' },
  { id: 'lecheDesn', name: 'Leche desnatada', kcal: 70, protein: 6.5, fat: 0.3, carbs: 10, fiber: 0, examples: '200ml leche desnatada' },
  { id: 'yogur', name: 'Yogur natural', kcal: 60, protein: 4, fat: 3, carbs: 5, fiber: 0, examples: '1 yogur (125g)' },
  { id: 'queso', name: 'Queso semicurado', kcal: 350, protein: 25, fat: 27, carbs: 1, fiber: 0, examples: 'Por 100g' },
  { id: 'legumbre', name: 'Legumbres', kcal: 330, protein: 22, fat: 2, carbs: 55, fiber: 15, examples: 'Lentejas, garbanzos, judías (100g seco)' },
  { id: 'frutoSeco', name: 'Frutos secos', kcal: 600, protein: 18, fat: 52, carbs: 15, fiber: 8, examples: 'Almendras, nueces, avellanas (100g)' },
  { id: 'aceite', name: 'Aceite/Grasa', kcal: 90, protein: 0, fat: 10, carbs: 0, fiber: 0, examples: '1 cucharada (10ml) AOVE' },
];

export const PATHOLOGY_PROFILES: Record<string, PathologyProfile> = {
  dm2: {
    key: 'dm2',
    name: 'Diabetes Mellitus tipo 2',
    fe: 1.0,
    protGkg: 1.2,
    grasasPct: 30,
    micros: { sodio: { max: 2000, unit: 'mg' }, fibra: { min: 30, unit: 'g' } },
    note: 'Bajo IG · Fibra >30g · HC complejos · Evitar azúcares simples · ESPEN: HC 45-60% VCT',
    espenMacros: 'HC 45-60% (bajo IG) · Prot 1.0-1.2 g/kg · Grasas <35% (MUFA prioritario)',
    meds: { metformina: 'Sin restricciones alimentarias específicas', sintrom: '⚠️ CONTROLAR Vitamina K: mantener ingesta estable de verduras A/B', insulina: 'Sincronizar HC con horario de inyección' },
  },
  hta: {
    key: 'hta',
    name: 'Hipertensión arterial',
    fe: 1.0,
    protGkg: 1.0,
    grasasPct: 30,
    micros: { sodio: { max: 1500, unit: 'mg' }, potasio: { min: 3500, unit: 'mg' } },
    note: 'Dieta DASH · Na <1500mg · Potasio alto · Calcio y Magnesio',
    espenMacros: 'Na <2g/día (5g sal) · K >3.5g/día · Prot 0.8-1.0 g/kg · Grasas 30%',
    meds: { enalapril: 'Evitar exceso de potasio (suplementos)', losartan: 'Evitar exceso de potasio', sintrom: '⚠️ Vitamina K estable' },
  },
  irc: {
    key: 'irc',
    name: 'Insuficiencia renal crónica',
    fe: 1.0,
    protGkg: 0.8,
    grasasPct: 35,
    micros: { sodio: { max: 2000, unit: 'mg' }, potasio: { max: 2000, unit: 'mg' }, fosforo: { max: 800, unit: 'mg' } },
    note: 'Prot 0.6-0.8g/kg prediálisis · K y P controlados · Na moderado',
    espenMacros: 'Prediálisis: Prot 0.6-0.8 g/kg · Diálisis: Prot 1.0-1.2 g/kg · Energía 25-35 kcal/kg',
    meds: {},
  },
  dislipemia: {
    key: 'dislipemia',
    name: 'Dislipemia',
    fe: 1.0,
    protGkg: 1.2,
    grasasPct: 30,
    micros: {},
    note: 'Grasas saturadas <7% · Aumentar omega-3 · Fibra >25g',
    espenMacros: 'Grasas saturadas <7% VCT · MUFA 15-20% · PUFA 6-10% · Fibra soluble >10g',
    meds: { atorvastatina: 'Evitar pomelo/zumo de pomelo', simvastatina: 'Evitar pomelo' },
  },
  sobrepeso: {
    key: 'sobrepeso',
    name: 'Sobrepeso / Obesidad',
    fe: 1.0,
    protGkg: 1.2,
    grasasPct: 30,
    micros: {},
    note: 'Déficit -500kcal · Alta fibra · Alta saciedad · Densidad nutricional',
    espenMacros: 'Déficit 500-750 kcal/día · Prot 1.2-1.5 g/kg peso ajustado · Fibra >30g',
    ajusteKcal: -500,
    meds: {},
  },
  embarazo: {
    key: 'embarazo',
    name: 'Embarazo',
    fe: 1.1,
    protGkg: 1.5,
    grasasPct: 30,
    micros: {},
    note: '+0 kcal 1ºT · +340 kcal 2ºT · +452 kcal 3ºT · Ác. fólico · Hierro · DHA',
    espenMacros: '1ºT: +0 kcal · 2ºT: +340 kcal · 3ºT: +452 kcal · Prot 1.1 g/kg · DHA ≥200mg',
    ajusteKcal: 300,
    meds: {},
  },
  deportista: {
    key: 'deportista',
    name: 'Alto rendimiento deportivo',
    fe: 1.0,
    protGkg: 1.8,
    grasasPct: 25,
    micros: {},
    note: 'Prot 1.6-2.2g/kg · Timing periworkout · HC alto · Hidratación',
    espenMacros: 'Prot 1.6-2.2 g/kg · HC 5-8 g/kg (resistencia) · Grasas 20-25%',
    meds: {},
  },
  celiaco: {
    key: 'celiaco',
    name: 'Enfermedad celíaca',
    fe: 1.0,
    protGkg: 1.2,
    grasasPct: 30,
    micros: {},
    note: 'Sin gluten estricto · Vigilar hierro, calcio, B12, folato',
    espenMacros: 'Sin gluten estricto · Suplementar Fe, Ca, B12, folato si déficit',
    meds: {},
  },
  epoc: {
    key: 'epoc',
    name: 'EPOC',
    fe: 1.0,
    protGkg: 1.4,
    grasasPct: 40,
    micros: {},
    note: '↑ Grasas 35-40% · ↓ HC 40-45% (menor producción CO₂) · Comidas pequeñas y frecuentes',
    espenMacros: 'Energía 30-35 kcal/kg · Prot 1.2-1.5 g/kg · Grasas 35-40% · HC 40-45% · ESPEN: reducir cociente respiratorio',
    meds: {},
  },
  cirrosis: {
    key: 'cirrosis',
    name: 'Cirrosis hepática',
    fe: 1.0,
    protGkg: 1.3,
    grasasPct: 30,
    micros: { sodio: { max: 2000, unit: 'mg' } },
    note: '35 kcal/kg/día · Prot 1.2-1.5g/kg · 5-6 comidas · Snack nocturno · AACR si encefalopatía',
    espenMacros: 'Energía 35 kcal/kg/día · Prot 1.2-1.5 g/kg · NO restringir proteínas · Snack nocturno HC',
    meds: {},
  },
  pancreatitis: {
    key: 'pancreatitis',
    name: 'Pancreatitis',
    fe: 1.2,
    protGkg: 1.5,
    grasasPct: 20,
    micros: {},
    note: 'Grasas <20% VCT · TCM si malabsorción · Enzimas pancreáticas · Alcohol cero',
    espenMacros: 'Grasas <20% VCT · TCM como fuente lipídica · Prot 1.0-1.5 g/kg · Abstinencia alcohol total',
    meds: {},
  },
  oncologico: {
    key: 'oncologico',
    name: 'Cáncer (soporte nutricional)',
    fe: 1.2,
    protGkg: 1.5,
    grasasPct: 35,
    micros: {},
    note: 'Prot 1.2-2.0g/kg · Evitar desnutrición · ONS si ingesta <60% · EPA/DHA 2g/día',
    espenMacros: 'Energía 25-30 kcal/kg · Prot 1.2-2.0 g/kg · EPA+DHA ≥2g/día · Suplementos orales si ingesta <60%',
    meds: {},
  },
  sinpat: {
    key: 'sinpat',
    name: 'Sin patología específica',
    fe: 1.0,
    protGkg: 1.2,
    grasasPct: 30,
    micros: {},
    note: 'Alimentación equilibrada · Dieta mediterránea como base',
    espenMacros: 'HC 45-55% · Prot 0.8-1.2 g/kg · Grasas 25-35% · Fibra ≥25g',
    meds: {},
  },
};

export const FOOD_EQUIVALENCIAS = {
  Frutas: {
    porcion: '150g',
    equiv: [
      { nombre: '1 manzana mediana', g: 150 },
      { nombre: '1 naranja grande', g: 200 },
      { nombre: '1 plátano mediano', g: 120 },
      { nombre: '2 kiwis', g: 150 },
      { nombre: '1 taza fresas', g: 150 },
      { nombre: '1 tajada sandía', g: 200 },
      { nombre: '1 pera mediana', g: 160 },
      { nombre: '½ taza arándanos', g: 75 },
      { nombre: '1 melocotón', g: 150 },
      { nombre: '10 uvas', g: 80 },
    ],
  },
  'Cereales/HC': {
    porcion: '30g HC',
    equiv: [
      { nombre: '1 rebanada pan integral', g: 40 },
      { nombre: '3 cda arroz cocido', g: 60 },
      { nombre: '½ taza pasta cocida', g: 70 },
      { nombre: '3 galletas integrales', g: 30 },
      { nombre: '½ taza avena cocida', g: 80 },
      { nombre: '1 tortilla de maíz', g: 30 },
      { nombre: '2 tostadas', g: 30 },
      { nombre: '½ taza quinoa cocida', g: 80 },
      { nombre: '1 papa pequeña', g: 80 },
      { nombre: '½ taza legumbres cocidas', g: 80 },
    ],
  },
  Proteínas: {
    porcion: '100g',
    equiv: [
      { nombre: '1 filete pechuga pollo', g: 120 },
      { nombre: '1 filete merluza', g: 130 },
      { nombre: '2 huevos', g: 100 },
      { nombre: '1 lata atún', g: 80 },
      { nombre: '100g tofu firme', g: 100 },
      { nombre: '½ taza legumbres secas', g: 60 },
      { nombre: '1 filete ternera', g: 120 },
      { nombre: '100g salmón', g: 100 },
      { nombre: '3 claras', g: 100 },
      { nombre: '80g jamón serrano', g: 80 },
    ],
  },
  Grasas: {
    porcion: '10g',
    equiv: [
      { nombre: '1 cda AOVE', g: 10 },
      { nombre: '6 almendras', g: 10 },
      { nombre: '3 nueces', g: 10 },
      { nombre: '¼ aguacate', g: 30 },
      { nombre: '1 cda mantequilla', g: 10 },
      { nombre: '1 cda semillas lino', g: 10 },
      { nombre: '1 cda semillas chía', g: 10 },
      { nombre: '1 cda tahini', g: 10 },
    ],
  },
  Lácteos: {
    porcion: '200ml / 1 ración',
    equiv: [
      { nombre: '1 vaso leche', g: 200 },
      { nombre: '2 yogures naturales', g: 250 },
      { nombre: '1 yogur griego', g: 150 },
      { nombre: '30g queso curado', g: 30 },
      { nombre: '60g queso fresco', g: 60 },
      { nombre: '1 vaso kéfir', g: 200 },
      { nombre: '200ml bebida soja', g: 200 },
      { nombre: '1 vaso leche sin lactosa', g: 200 },
    ],
  },
  Verduras: {
    porcion: '200g',
    equiv: [
      { nombre: '1 plato ensalada mixta', g: 200 },
      { nombre: '1 taza brócoli cocido', g: 150 },
      { nombre: '2 tomates medianos', g: 200 },
      { nombre: '1 taza espinacas crudas', g: 50 },
      { nombre: '1 zanahoria grande', g: 100 },
      { nombre: '½ calabacín', g: 150 },
      { nombre: '1 taza judías verdes', g: 150 },
      { nombre: '1 taza coliflor', g: 150 },
    ],
  },
};
