// Meal Plan Generator routes — Drizzle ORM
import { Router } from 'express';
import { eq, desc, and } from 'drizzle-orm';

import { db } from '../config/db.js';
import { mealPlanTemplates, mealPlanDays, foods } from '../db/schema/index.js';
import { authenticate } from '../middleware/auth.js';
import { validateZod } from '../middleware/zodValidate.js';
import { MealPlanGenerateSchema, MealPlanTemplateSchema } from '../schemas/index.js';
import { logAudit } from '../utils/audit.js';

const router = Router();

interface FoodRow {
  id: string;
  name: string;
  caloriesPer100g: string | null;
  proteinPer100g?: string | null;
  carbsPer100g?: string | null;
  fatPer100g?: string | null;
  allergens?: string | null;
}

function generateMealPlan(objectives: { calories: number; allergens?: string[]; durationDays: number }, foodRows: FoodRow[]) {
  const { calories, allergens = [], durationDays } = objectives;
  const mealTypes = ['desayuno', 'almuerzo', 'cena', 'colacion'];
  const mealRatios = [0.25, 0.35, 0.30, 0.10];
  const plan = [];
  for (let day = 1; day <= durationDays; day++) {
    const dayMeals = [];
    const dayUsedFoods = new Set<string>();
    for (let m = 0; m < mealTypes.length; m++) {
      const mealCalories = Math.round(calories * mealRatios[m]);
      let available = foodRows.filter(f => !allergens.some((a: string) => (f.allergens || '').includes(a)));
      available = available.filter((f) => !dayUsedFoods.has(f.id));
      const selected = [];
      let currentCal = 0;
      const shuffled = available.sort(() => Math.random() - 0.5);
      for (const food of shuffled) {
        if (currentCal >= mealCalories * 0.9 && currentCal <= mealCalories * 1.1) break;
        const portion = Math.round((parseFloat(food.caloriesPer100g ?? '0') / parseFloat(food.caloriesPer100g || '1')) * 100);
        if (portion > 0 && portion <= 1000) {
          selected.push({ foodId: food.id, name: food.name, portion, calories: Math.round(parseFloat(food.caloriesPer100g ?? '0') * portion / 100), protein: Math.round(parseFloat(food.proteinPer100g || '0') * portion / 100), carbs: Math.round(parseFloat(food.carbsPer100g || '0') * portion / 100), fat: Math.round(parseFloat(food.fatPer100g || '0') * portion / 100) });
          currentCal += Math.round(parseFloat(food.caloriesPer100g ?? '0') * portion / 100);
          dayUsedFoods.add(food.id);
        }
      }
      dayMeals.push({ type: mealTypes[m], time: m === 0 ? '08:00' : m === 1 ? '13:00' : m === 2 ? '20:00' : '16:00', foods: selected, totalCalories: currentCal });
    }
    plan.push({ day, meals: dayMeals, totalCalories: dayMeals.reduce((sum: number, m: { totalCalories: number }) => sum + m.totalCalories, 0) });
  }
  return plan;
}

router.post('/generator/generate', authenticate, validateZod(MealPlanGenerateSchema), async (req, res) => {
  try {
    const user = req.user;
    if (!user) return res.error(401, 'Unauthorized');
    const objectives = req.body;
    const foodRows = await db.select().from(foods).limit(200);
    if (!foodRows.length) return res.error(400, 'No hay alimentos disponibles');
    const plan = generateMealPlan(objectives, foodRows);
    const templateResult = await db.insert(mealPlanTemplates).values({
      name: `Plan auto ${new Date().toLocaleDateString()}`, objectives, durationDays: objectives.durationDays, isAutoGenerated: true, createdBy: user.id,
    }).returning();
    const template = templateResult[0];
    for (const day of plan) {
      await db.insert(mealPlanDays).values({ planTemplateId: template.id, dayNumber: day.day, meals: day.meals, totalCalories: day.totalCalories });
    }
    await logAudit(user.id, 'CREATE', 'MealPlanTemplate', template.id, req);
    res.created({ template, plan });
  } catch (err) { console.error(err); res.error(500, 'Error interno'); }
});

router.get('/generator/templates', authenticate, async (req, res) => {
  try {
    const user = req.user;
    if (!user) return res.error(401, 'Unauthorized');
    const r = await db.select().from(mealPlanTemplates).where(eq(mealPlanTemplates.createdBy, user.id)).orderBy(desc(mealPlanTemplates.createdAt));
    res.success(r);
  } catch (err) { res.error(500, 'Error interno'); }
});

router.get('/generator/templates/:id', authenticate, async (req, res) => {
  try {
    const user = req.user;
    if (!user) return res.error(401, 'Unauthorized');
    const r = await db.select().from(mealPlanTemplates).where(eq(mealPlanTemplates.id, req.params.id));
    if (!r.length) return res.error(404, 'Template no encontrado');
    const days = await db.select().from(mealPlanDays).where(eq(mealPlanDays.planTemplateId, req.params.id));
    res.success({ ...r[0], days: days.sort((a, b) => (a.dayNumber || 0) - (b.dayNumber || 0)) });
  } catch (err) { res.error(500, 'Error interno'); }
});

router.post('/generator/templates', authenticate, validateZod(MealPlanTemplateSchema), async (req, res) => {
  try {
    const user = req.user;
    if (!user) return res.error(401, 'Unauthorized');
    const { name, objectives, durationDays, isAutoGenerated } = req.body;
    const r = await db.insert(mealPlanTemplates).values({ name, objectives, durationDays, isAutoGenerated, createdBy: user.id }).returning();
    await logAudit(user.id, 'CREATE', 'MealPlanTemplate', r[0].id, req);
    res.created(r[0]);
  } catch (err) { res.error(500, 'Error interno'); }
});

router.put('/generator/templates/:id', authenticate, validateZod(MealPlanTemplateSchema.partial()), async (req, res) => {
  try {
    const user = req.user;
    if (!user) return res.error(401, 'Unauthorized');
    const updates: Record<string, unknown> = {};
    if (req.body.name !== undefined) updates.name = req.body.name;
    if (req.body.objectives !== undefined) updates.objectives = req.body.objectives;
    if (req.body.durationDays !== undefined) updates.durationDays = req.body.durationDays;
    if (req.body.isAutoGenerated !== undefined) updates.isAutoGenerated = req.body.isAutoGenerated;
    const r = await db.update(mealPlanTemplates).set(updates).where(and(eq(mealPlanTemplates.id, req.params.id), eq(mealPlanTemplates.createdBy, user.id))).returning();
    if (!r.length) return res.error(404, 'Template no encontrado');
    await logAudit(user.id, 'UPDATE', 'MealPlanTemplate', req.params.id, req);
    res.success(r[0]);
  } catch (err) { res.error(500, 'Error interno'); }
});

router.delete('/generator/templates/:id', authenticate, async (req, res) => {
  try {
    const user = req.user;
    if (!user) return res.error(401, 'Unauthorized');
    const r = await db.delete(mealPlanTemplates).where(and(eq(mealPlanTemplates.id, req.params.id), eq(mealPlanTemplates.createdBy, user.id))).returning({ id: mealPlanTemplates.id });
    if (!r.length) return res.error(404, 'Template no encontrado');
    await logAudit(user.id, 'DELETE', 'MealPlanTemplate', req.params.id, req);
    res.success({ id: req.params.id });
  } catch (err) { res.error(500, 'Error interno'); }
});

export default router;